[package]
name = "faer-traits"
version = "0.21.3"
edition = "2021"
authors = ["sarah quiñones <sarah@veganb.tw>"]
description = "linear algebra library"
readme = "../README.md"
repository = "https://github.com/sarah-quinones/faer-rs/"
license = "MIT"
keywords = ["math", "linear-algebra"]

[dependencies]
bytemuck = "1.18.0"
reborrow = "0.5.5"
generativity = "1.1.0"
libm = "0.2.8"

dyn-stack = { version = "0.13.0", default-features = false, features = ["core-error", "alloc"] }
pulp = { version = "0.21.3", default-features = false }
faer-macros = { path = "../faer-macros", version = "0.21.0" }

num-complex = { version = "0.4.6", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
